### ISSUE TITLE
Due Date - Project Requirements

### ISSUE THREAD

**Issue by PrimalOrB** [PrimalOrB/myBid#12]
- [x] Use React for the front end. #1 

- [x] Use GraphQL with a Node.js and Express.js server. #1 

- [x] Use MongoDB and the Mongoose ODM for the database. #1 

- [x] Use queries and mutations for retrieving, adding, updating, and deleting data.

- [x] Be deployed using Heroku (with data). #13 

- [x] Have a polished UI. #10 

- [x] Be responsive. #11 

- [x] Be interactive (i.e., accept and respond to user input). #1 #4 #5 

- [x] Include authentication (JWT). #1 

- [x] Protect sensitive API key information on the server. #13 

- [x] Have a clean repository that meets quality coding standards (file structure, naming conventions, best practices for class and id naming conventions, indentation, high-quality comments, etc.).

- [x] Have a high-quality README (with unique name, description, technologies used, screenshot, and link to deployed application). #19
