### ISSUE TITLE
MVP - Auction End Functionality

### ISSUE THREAD

**Issue by PrimalOrB** [PrimalOrB/myBid#21]
- [ ] when auction time ends ( Auction Model endDate / activeStatus ) #7 
- [ ] was the auction reserve met? ( Auction Model auctionInfo.reserveMet) #7 
- [ ] what is the value of the max bid  ( Auction Model auctionInfo.reserveMet) #7 
- X are there multiple bids at the max value? (not sure how that typically gets handled) (not an issue, as the bids must be greater than current to value to count)
- [ ]  define winner  ( Auction Model auctionInfo.reserveMet) #7

**Comment by PrimalOrB** [comment]
so a lot of this data will be determined already by the Auction virtual property of` ``auctionInfo``, so it will be figuring how to action that in terms of triggering things like emails to winners, etc
